### ISSUE TITLE
authUser wiki update

### ISSUE THREAD

**Issue by Jboonie** [pwillworth/galaxyharvester#10]
The [authUser ](https://github.com/pwillworth/galaxyharvester/wiki/authUser#response-plain-text) wiki entry does not appear to be accurate based on the source code, at least that has been my experience when trying to auth via a custom app.

**Current wording reads:**

Request Parameters

    loginp: Galaxy Harvester user name
    passp: Galaxy Harvester user password

**Proposed Change:**

Request Parameters

    loginu: Galaxy Harvester user name
    passu: Galaxy Harvester user password

This changed is based on: https://github.com/pwillworth/galaxyharvester/blob/master/html/authUser.py

Lines 54 & 55:

loginp = form.getfirst('loginu')
passp = form.getfirst('passu')

When I send post requests with loginp and passp I get a no turn, when I utilize loginu and passu I get a successful request.

**Comment by cbortz** [comment]
@Jboonie I think you're correct. It looks like the wiki article is referencing the variable names rather than the parameter names. Good catch, and thanks for sharing!

**Comment by cbortz** [comment]
@Jboonie The wiki article has been updated. Thanks again for sharing this!
