### ISSUE TITLE
postResource.py Proposed Wiki Change

### ISSUE THREAD

**Issue by Jboonie** [pwillworth/galaxyharvester#11]
Good morning, sorry to send out another post but I ran into another documentation issue with the postResource.py [wiki](https://github.com/pwillworth/galaxyharvester/wiki/postResource) yesterday that I think could be beneficial to modify.

**Currently the documentation states:**

galaxy: Galaxy Harvester user name
planet: Galaxy Harvester user password

This is incorrect.

**Proposed modifications:**

**gh_sid**: Session token value provided by authentication utilizing [authUser.py](https://github.com/pwillworth/galaxyharvester/wiki/authUser).

**galaxy**: This is the numeric galaxy ID for the target server.  This can be found by clicking on a specific resource located on the target server example: http://www.galaxyharvester.net/resource.py/ **14** /kaipi.

**planet**: The planet the resource inhabits.  A list of valid entries can be found in the planet.csv seed data [here](https://github.com/pwillworth/galaxyharvester/blob/master/database/seedData/planet.csv).

**resID**: Numeric resource spawn ID. This is not required but can be utilized instead of resName.

**resName**: Resource spawn name. This is not required but can be utilized instead of resID.

**resType**: Name of resource type. Example: "aluminum_agrinium". If your data is coming from the core3 .lua file, the type header is a valid entry.  Valid entries can be located in seed data [here](https://github.com/pwillworth/galaxyharvester/blob/master/database/seedData/tResourceType.txt).

**forceOp**: Can be set to (edit or verify) to indicate post is to edit or verify an existing resource.  for adds, you can just pass "add" via this field.

I think that adding either this or something like this would make it much easier for people to get up and running utilizing the postResource service.  I think it might also be beneficial some guidelines about appropriate post rates so that people don't flood the application.

Thanks for taking the time to consider!

**Comment by pwillworth** [comment]
Hey thanks, yeah these updates would be great, I'll get them added.
