### ISSUE TITLE
"More" button on recent activity doesn't work properly

### ISSUE THREAD

**Issue by jdcoolha** [pwillworth/galaxyharvester#14]
Pressing "More" on a user's recent activity list just repeats the same recent activity and doesn't add anything new.

**Comment by cbortz** [comment]
Thanks for the submission @jdcoolha. I've confirmed this one @pwillworth with the profile http://galaxyharvester.net/user.py/jawsont

**Start of activity**
![image](https://user-images.githubusercontent.com/184307/68552300-83af8880-03e3-11ea-8fb0-df99313ba2a0.png)

**Activity after clicking "More"**
![image](https://user-images.githubusercontent.com/184307/68552308-a346b100-03e3-11ea-8c83-16ffdef7354b.png)

**Comment by cbortz** [comment]
@jdcoolha are you planning on opening a pull request to fix this? (No pressure to, just curious)

**Comment by jdcoolha** [comment]
@cbortz Don't have the time or ability to do so right now, sorry.

**Comment by pwillworth** [comment]
Commit [09d53b9](https://github.com/pwillworth/galaxyharvester/commit/09d53b93b66d182036025d3e11bffb82a542f7f1) resolved issue and deployed.
