### ISSUE TITLE
Breaks not parsed in "In Game Names" Field

### ISSUE THREAD

**Issue by jdcoolha** [pwillworth/galaxyharvester#15]
Instead of line breaks, it puts "\n" between names.

This...
![image](https://user-images.githubusercontent.com/1365088/68552288-61b60600-03e3-11ea-8dd1-ded37ffdc991.png)

Becomes this.
![image](https://user-images.githubusercontent.com/1365088/68552290-64186000-03e3-11ea-9055-eeaf51f50ed6.png)

**Comment by cbortz** [comment]
Thanks for submitting @jdcoolha! I think I've noticed this one in the past, but I'm unsure what the actual intended behavior is.

@pwillworth is the intended behavior to parse newlines?

**Comment by pwillworth** [comment]
@cbortz Not necessarily intended to parse newlines, but I think that would be fine.  At the very least it should put a space rather than escaped n, so seems a valid bug for that at least.

**Comment by Deedjee** [comment]
Hello,
I'm not a contributor but i installed and use GH for my own guild.
I noticed that when submitting a Flora droid report, only the "flora food" and "flora structural" de spawn is treated correctly.
For Creature and food and structural the old spawn is not removed and i must parse manually the list to remove the old one. 
We should always have as a result 13 creature food, 7 creature structural for each planet.
Anyway I'm very happy using this awesome tool. :)

**Comment by cbortz** [comment]
Thanks for the comment @Deedjee. It seems like you're trying to submit a _new_ issue (rather than add details to this one). Can you please submit your new issue using [this link](https://github.com/pwillworth/galaxyharvester/issues/new)?

**Comment by pwillworth** [comment]
https://github.com/pwillworth/galaxyharvester/commit/2aa3de9450899ca6d10a9b3978d2c00b8ad686af
