### ISSUE TITLE
Creature food and Creature structural old spawns not removed with new droid report

### ISSUE THREAD

**Issue by Deedjee** [pwillworth/galaxyharvester#16]
When submitting a new Flora droid report, only the "flora food" and "flora structural" old spawns are treated correctly (removed).
For Creature food and creature structural the old spawn is not removed and we must parse manually the list to remove it.
We should always have as a result 13 creature food type , 7 creature structural type for each planet.

**Comment by cbortz** [comment]
Thanks for submitting a new issue, @Deedjee I don't know much about this feature. We'll see if @pwillworth is able to weigh in and confirm this or not.

**Comment by pwillworth** [comment]
@Deedjee Not sure why you would expect creature resource spawns to be removed when you submit a flora survey droid report.  The system only cleans up old resources of the same type as the type of resources for the survey report.  This is as designed.

When someone posts a new creature resource through the add resource area on the site, it will prompt them if they want to remove the old one.  That is when creature resources would be cleaned up.

**Comment by Deedjee** [comment]
Hi Paul,
_"The system only cleans up old resources of the same type as the type of resources for the survey report."_
I agree, it works for Flora Food and Flora Structural , but not for Creature Food and Creature Structural which have one unique spawn for each type (ex; 1milk 1 wild meat etc..) for a given Planet.
But when submitting the droid report we have duplicated types in these two categories, like for instance two Corellian wild milk , the old and the new one , where we should have only one.

**Comment by pwillworth** [comment]
Are you saying you submit survey droid reports for creature resources?  If so, can you provide an example of the mail file?

**Comment by Deedjee** [comment]
Sure, 
The one enclosed for example, received yesterday.
NB:
I have no errors during the upload.
I run GH on my own server but the result is the same on the offficial one (i did the test with the same files on both servers).
The old spawn of Flora food & structure are correctly removed , not the one of creature food and structure.

[228282255.txt](https://github.com/pwillworth/galaxyharvester/files/4611603/228282255.txt)

**Comment by pwillworth** [comment]
I see, thanks for providing the example.

In this case, the server you are working with has some custom code implemented that adds Creature Resources to the Flora Resources survey droid report.

Galaxy Harvester is depending on the contents of the report to match the class of resources specified at the top of the report.  In this case, it is Flora_resources.  After the import, it cleans up old resources that are of that class.  For reference, see the resource tree here for how the different classes relate to each other: [Resource Type Tree](http://galaxyharvester.net/resourceType.py)

I would suggest a different implementation of the server code to provide a separate resource report for creature resources with the proper class header indicating "Creature_resources".  I don't think we want to alter the Galaxy Harvester code to account for some custom server code that does not report resources under the class they are related to.

**Comment by Deedjee** [comment]
Thanks for the clear explanation. That's fine, i was just wondering why the different treatments of old spawns between the two classes , Flora and Creature.
I will suggest it to the server owner (Aurora), just for his information.
