### ISSUE TITLE
Jumbled layout in more detailed Resource List Layout

### ISSUE THREAD

**Issue by pwillworth** [pwillworth/galaxyharvester#35]
It seems that recently the resource boxes that display in the long format with the extra info like on the [resource list](http://galaxyharvester.net/resourceList.py?) page have thier components jumbled now.
How they look now:
![jumble](https://user-images.githubusercontent.com/11822353/131183681-aa7c8c94-2dc5-4c30-a686-d0804800daa9.png)
How they should look:
![correct](https://user-images.githubusercontent.com/11822353/131183708-62a5f9bd-dff0-4266-aa89-539ce3f35ed6.png)

components should not overlap and should spread out to fill the width of the container

**Comment by MrKraken** [comment]
42dc471
