### ISSUE TITLE
Planet name missing from hover text on planet bar when available

### ISSUE THREAD

**Issue by pwillworth** [pwillworth/galaxyharvester#36]
Looks like the planet name is included in the hover text message when you hover over a planet that is not available, but is missing when the planet is marked available.
![planethover](https://user-images.githubusercontent.com/11822353/131184092-33189dad-3846-4d01-99ac-af118e578494.png)
The hover message in this picture should instead say "Lok marked available by TarkinSWG"

**Comment by MrKraken** [comment]
ee266a8
