### ISSUE TITLE
survey droid interface occludes resource data entry on small screens

### ISSUE THREAD

**Issue by pwillworth** [pwillworth/galaxyharvester#37]
If you are viewing the add resources page on a tablet trying to enter resource data, the boxes beyond OQ get occluded by the survey droid interface.  All the stat fields should be visible regardless of browser width.
![droidinway](https://user-images.githubusercontent.com/11822353/131185563-f3919830-a5c1-4284-9318-c5fff1b8a42a.png)

**Comment by MrKraken** [comment]
Part of a wider issue with responsiveness to be honest, needs some heavy refactoring all over to slap a flex based grid in there. Drilling bootstrap in is on my list of things to tackle. I'd say a temporary solution would be to put the SDI on the left side of the page or `overflow:auto;` the addResBox

**Comment by pwillworth** [comment]
Yeah, agree, lots to be desired on the layout stuff all over, had a user report this the other day, so they'll appreciate getting at least a band-aid for now.
