### ISSUE TITLE
`getComponentList.py` excludes manually-entered components

### ISSUE THREAD

**Issue by cbortz** [pwillworth/galaxyharvester#58]
Manually-entered component schematics are not included in this list, and therefore not available as components in other schematics. For example:

1. Create a new schematic for an Armor Component, choosing manual entry
    + set **Crafting Tab** to `Armor`
    + set **Object Type** to `Armor Schematic`
2. Create a new armor schematic
3. Edit the armor schematic
4. Choose "Component" from the Ingredient Selector
5. Choose "Armor" from the filter

You won't see the Armor Component from step 1.

This also applies to any components copied from manually-entered component schematics.

---

Diving in a bit, it looks like there's two conditions for a component schematic to be included in the list:

- its `tSchematic.craftingTab` matches the filtered crafting tab (required)
- either:
    + `tSchematic.objectGroup` contains `"component"` in the path, or
    + `tSchematic.objectType` is equal to `262144` (one of the generic "Component" types)

The problem here is that manually-entered schematics do not set an `objectGroup`. The code sets it to an empty string. Therefore it can never match `%component%`. A possible workaround is to select the "_correct_" `objectType` (there are 4 or 5 of them).

As for solutions, I think we could:

1. join on `tObjectType` and add an `OR` condition where `tObjectType.typeName LIKE "%component%"`
2. extend the condition for `tSchematic.objectType` to use an `IN` syntax with a list of object type IDs

Personally, I'm inclined to start with option 1, as its fairly obvious (e.g. any object type with the word "component" in it) and gives us backward-and-forward-compatibility. I'm going to open a PR with this proposed change, but open to other proposals!

**Comment by cbortz** [comment]
For example, this is an Armor Component is not listed in the Armor components: https://galaxyharvester.net/schematics.py/Armor_Core64 (Server ID `64`)

**Comment by pwillworth** [comment]
Hmmm, yeah after looking at this, I think I remember that the only valid way to add a component that was selectable was to copy from another component schematic as a starting point.  I think I wanted to make the Object Group editable on the schematic at some point to improve that, but can't remember if there was something holding me back from that.

**Comment by cbortz** [comment]
> Hmmm, yeah after looking at this, I think I remember that the only valid way to add a component that was selectable was to copy from another component schematic as a starting point. I think I wanted to make the Object Group editable on the schematic at some point to improve that, but can't remember if there was something holding me back from that.

Is there a reason we shouldn't consider an Object Type of `Armor Component` as an _armor component_?
