### ISSUE TITLE
Add exact Python/Stack versions to README

### ISSUE THREAD

**Issue by cbortz** [pwillworth/galaxyharvester#7]
@pwillworth I am planning to make a couple PRs here in the near future, but I know last time there was an issue with the version of Python I was using.

You'll see that in https://github.com/pwillworth/galaxyharvester/commit/0f9187a5e3b2972ccb7ebba0a8dd940543d184a6, I had to make a change in the syntax for Python 2.7 to process the line properly. Subsequently in https://github.com/pwillworth/galaxyharvester/commit/c100db864cf3839588c1a921a164cbde6662de8d, you reverted those changes (assuming they broke something locally for you and/or on the production environment). I'm not 💯 sure, but I think this may be the result of conflicting versions of Python (or another part of the stack).

Can you update the README to include the exact version of Python and all other required items in the tech stack?

- Python
- MySQL
- python-MySQLdb
- jinja2

**Comment by pwillworth** [comment]
Yeah, I think it is probably more specifically different syntax on different versions of the python-mysqldb module.  The version of the module running in the production environment was not happy with that trailing comma.  I'll get the versions that are running on the hosting provider added to that README, that will be good.

**Comment by cbortz** [comment]
Thanks, Paul!
